### PR TITLE
🎯 Math Magicians | Setup Project 🎯

### PR DESCRIPTION
**Pull request by Rysth**
# 🏅 Features Implemented
_Project Requirements -> https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_setup.md_

List of things that were implemented based on the requirements:

## 📝 General requirements

- ✅ No Linters errors.
- ✅ Used GitFlow correctly.
- ✅ Created a professional `README` file.

## 📝 JavaScript requirements

- ✅ Followed the best JavaScript practices.

## 📝 Project requirements

- ✅ Installed [Node.js](https://nodejs.org/en/) on my machine.
- ✅ Created the project using [Create React App](https://create-react-app.dev/)
- ✅ Ran in the browser without problems.

## 📷 Screenshots

image

_John Palacios_
_Microverse Student_

### CODE REVIEW

**Review by julie-ify — COMMENTED** [review]
Hi @Rysth,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* You do not have a Future Features section on your readme file. Kindly add it.

* Your provided live demo link is not correct. It takes me to a broken github page link. Kindly fix the link or you can remove that section if you have no link.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by julie-ify — COMMENTED** [review]
Hi @Rysth,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* Kindly remove that live demo section if you have no live demo link, as requested earlier. That section should have a valid live demo or you should remove that section completely, and its section link on the headers.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Rysth** [comment]
Thanks! @julie-ify

**Review by julie-ify — APPROVED** [review]
Hi @Rysth,

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
